version: '3'
services:
  bdfr-html:                                #Container which runs both bdfr and bdfr-html
    container_name: bdfr-html
    build: .                                #Builds from current folder, could also build from git repo
    environment:                            
      - BDFRH_LOGLEVEL=INFO                 #Either INFO or DEBUG for more verbose logs
    volumes:
      - output:/bdfrh/output                #Shared docker volume between the script container and the webserver, could also be mounted to local filesystem
      #- ./output:/bdfrh/output             #An example of mounting to the local filesystem
      - ./config/:/bdfrh/config             #Config files for both bdfr and bdfr-html
    ports:
      - "7634:7634"                         #Port needed for oauth
  apache:                                   #Standard webserver serving the content of the output folder
    image: httpd:alpine
    container_name: bdfr-server
    ports:
      - "80:80"                             #Port for web server
    volumes:
      - output:/usr/local/apache2/htdocs/   #This should match the output volume or mount in the script container
      #- output:/usr/local/apache2/htdocs/  #An example of mounting to the local filesystem

volumes:
  output: